#!/bin/bash

echo "🚀 Deploying ImPACTS Sync Server to Render..."
echo ""
echo "📋 Prerequisites:"
echo "1. Create account at https://render.com"
echo "2. Connect your GitHub account"
echo "3. Have your BigQuery credentials ready"
echo ""
echo "📝 Steps to deploy:"
echo ""
echo "1. Push your code to GitHub:"
echo "   git add ."
echo "   git commit -m 'Add sync server for permanent deployment'"
echo "   git push origin main"
echo ""
echo "2. In Render dashboard:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Select your ImPACTS repository"
echo "   - Configure:"
echo "     * Name: impacts-sync-server"
echo "     * Environment: Node"
echo "     * Build Command: npm install"
echo "     * Start Command: node sync-server.js"
echo "     * Plan: Free"
echo ""
echo "3. Set environment variables:"
echo "   - REACT_APP_BIGQUERY_PROJECT_ID: impacts-tracker"
echo "   - REACT_APP_BIGQUERY_CREDENTIALS: [Your BigQuery JSON credentials]"
echo ""
echo "4. After deployment, you'll get a URL like:"
echo "   https://impacts-sync-server-abc123.onrender.com"
echo ""
echo "5. Update client code with the new URL and redeploy:"
echo "   cd client"
echo "   npm run build"
echo "   firebase deploy --only hosting"
echo ""
echo "✅ Your sync server will be permanently available!"
echo ""
echo "📖 For detailed instructions, see PERMANENT_DEPLOYMENT_GUIDE.md"





