-- DEPRECATED: use MANAGER_TIER_HARDENING.sql instead.
-- That script replaces hospitals_manager_all, adds secondary-manager scope,
-- tightens tab_visibility / permissions RLS, and allows manager cohort create.
